Machine.add("/docs/chuck/theremin/event.ck");
Machine.add("/docs/chuck/theremin/constants.ck");
Machine.add("setup.ck");
Machine.add("/docs/chuck/theremin/arduinoBroadcaster.ck");
Machine.add("/docs/chuck/theremin/keyboardBroadcaster.ck");
Machine.add("/docs/chuck/theremin/micLooper.ck");
Machine.add("samples.ck");
Machine.add("/docs/chuck/theremin/eventController.ck");
/*Machine.add("rec-l.ck");*/
/*Machine.add("rec-r.ck");*/
